services:
  # Banco principal
  api-hunterstackio-postgres:
    image: postgres:16
    user: root
    container_name: api-hunterstackio-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hunterstackio
      POSTGRES_PASSWORD: Verde*2025
      POSTGRES_DB: hunterstackio
    volumes:
      - ./db/postgres_main:/var/lib/postgresql/data

  # Banco shadow
  api-hunterstackio-postgres-shadow:
    image: postgres:16
    user: root
    container_name: api-hunterstackio-postgres-shadow
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: sd_hunterstackio
      POSTGRES_PASSWORD: Verde*2025
      POSTGRES_DB: sd_hunterstackio
    volumes:
      - ./db/postgres_shadow:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_shadow_data:
